const ResponseMessage = {
  USER_NOT_EXIST: "User not exist",
  DATABASE_CONNECTED: "Database connected",
  INTERNAL_SERVER_ERROR: "Internal server error",
  INCORRECT_CREDENTIALS: "Invalid credentials",
  NO_RECORDS_FOUND: "No records found",
  NO_RECORDS_AVAILABLE: "No records available",
  OTP_SENT_ON_MAIL: "Otp sent on your email address",
  OTP_RESENT_ON_MAIL: "Otp resent on your email address",
  EMAIL_OR_MOBILE_NOT_FOUND: "Email or mobile number not found",
  EMAIL_OR_MOBILE_REQUIRED: "Email or mobile number is required",
  PHONE_NUMBER_ALREADY_EXISTS: "Phone number already exists",
  ALL_FIELDS_ARE_REQUIRED: "All fields are required",
  VERIFICATION_COMPLETED: "Otp verification completed successfully",
  INVALID_OTP: "Invalid OTP",
  PASSWORD_AND_CONFIRM_PASSWORD: "Password and confirm password not match",
  OTP_NOT_VERIFY: "Otp not verify",
  OLD_PASSWORD_INVALID: "Invalid old password",
  OLD_PASSWORD_SAME: "Old and New password should not be same",
  RESET_PASSWORD: "Password reset successfully",
  YOU_ENTER_WRONG_PASSWORD: "You enter wrong old password",
  PASSWORD_CHANGED: "Your Password has been changed",
  PASSWORD_CHANGED_TO_FAILED: "Password change to failed",
  TOKEN_NOT_AUTHORIZED: "Token not authorized",
  EMAIL_ALREADY_EXIST: "Email Already Exist",
  PROFILE_UPDATED: "Profile updated successfully",
  FAILED_TO_UPDATE: "Failed to update",
  PLEASE_USE_DIFFRENT_PASSWORD: "Please use diffrent password",
  NEW_PASSWORD_AND_CONFIRM_PASSWORD_NOT_MATCH:
    "New and confirm password not match",
  ACCOUNT_NOT_EXIST: "Account not exist",
  FORGOT_PASSWORD_MAIL_SEND: "Forgot password mail send successfully",
  MAIL_NOT_SENT: "Mail not sent",
  OTP_MATCHED: "Otp has matched",
  OTP_INVALID: "Otp is invalid",
  DATA_GET_SUCCESSFULLY: "Data get successfully",
  USER_NOT_FOUND: "User not found",
  USER_DELETE: "User deleted successfully",
  USER_UPDATED: "User updated successfully",
};

module.exports = ResponseMessage;
